version: "2"
services:
  myminio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./test/.minio/data:/export
      - ./test/.minio/config:/root/.minio
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      #- "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE"
      #- "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    command: server /export --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - myminio
    volumes:
      - "./model:/tmp/model"
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://myminio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY) do echo '....wait...' && sleep 1; done;
      /usr/bin/mc rm -r --force myminio/somebucketname;
      /usr/bin/mc policy set public myminio/somebucketname;
      /usr/bin/mc cp --recursive /tmp/model myminio/somebucketname;
      "
  tf-serving:
    image: tensorflow/serving
    depends_on: 
     - createbuckets
    ports:
     - "8501:8501"
    environment:
     - "AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE"
     - "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
     - "MODEL_BASE_PATH=s3://somebucketname/model"
     - "MODEL_NAME=saved_model_half_plus_two_cpu"
     - "S3_ENDPOINT=http://myminio:9000"
   
  tf-client:
    image: python:3.8-bullseye
    depends_on: 
     - tf-serving
    environment:
     - "TF_HOST=tf-serving"
     - "TF_PORT=8501"
     - "TF_MODEL=saved_model_half_plus_two_cpu"
    volumes:
     - "./scripts:/scripts"
    entrypoint: >
     /bin/sh -c "python /scripts/request_prediction.py"
      
     
     
